# https://moonrepo.dev/docs/config/global-project
$schema: "https://moonrepo.dev/schemas/global-project.json"

fileGroups:
  configs:
    - "*.{js,json}"
  sources:
    - "src/**/*"
    - "types/**/*"
  tests:
    - "tests/**/*"

tasks:
  lint:
    command:
      - eslint

    args:
      - --no-error-on-unmatched-pattern
      - "."

    deps: []

    env:
      NODE_ENV: "production"

    inputs:
      - "@globs(sources)"

    type: "node"

  prettier:
    command:
      - prettier

    args:
      - --check
      - "."

    deps:
      - ^:lint

    env:
      NODE_ENV: "production"

    inputs:
      - "@globs(sources)"

    type: "node"

  build:
    command:
      - packemon

    args:
      - build
      - --addFiles
      - --addEngines
      - --declaration

    deps:
      - ^:lint
      - ^:prettier

    env:
      NODE_ENV: "production"

    inputs:
      - "@globs(sources)"

    outputs:
      - lib
      - dts

    type: "node"

  release:
    command:
      - packemon

    args:
      - pack
      - --addFiles
      - --addEngines
      - --declaration

    deps:
      - ^:lint
      - ^:prettier

    env:
      NODE_ENV: "production"

    inputs:
      - "@globs(sources)"

    outputs:
      - lib
      - dts

    type: "node"
